output_dir: /home/fanny/Documents/Work/HeartRate_Tox/output/
vcf_file: /home/fanny/Documents/Work/HeartRate_Tox/finemapping/data_finemapping/joint_stitch_output.vcf.gz

fasta_dir: /home/fanny/Documents/Work/fasta_medaka_panel/chr_fasta_ref/
sample_file: /home/fanny/Documents/Work/fasta_medaka_panel/cram_file_f2s_philip_filters2.txt

flexlmm_dir: /home/fanny/Documents/Work/HeartRate_Tox/finemapping/data_finemapping/after_norm/
phenotype_file: /home/fanny/Documents/Work/HeartRate_Tox/finemapping/data_finemapping/phenotypes_f2s.tsv
covariate_file: /home/fanny/Documents/Work/HeartRate_Tox/finemapping/data_finemapping/covariates_f2s_tank.tsv

info_file: /home/fanny/Documents/Work/HeartRate_Tox/finemapping/data_finemapping/Oryzias_latipes-GCA_002234675.1-2022_04-genes_clean.sorted.colored.gff3.gz
vep_file: /home/fanny/Documents/Work/HeartRate_Tox/finemapping/data_finemapping/vep_medaka_new_reference_release_94.txt.gz
